### ISSUE TITLE
how to convert yml to js file

### ISSUE THREAD

**Issue by tombohub** [davidtheclark/cosmiconfig#244]
If we have this yml:

```
schema: http://localhost:3000/graphql
documents: ./src/**/*.graphql
generates:
  ./src/types.ts:
    plugins:
      - typescript
      - typescript-operations
```

how to convert to js file that cosmiconfig will understand?
